name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'  # Consider changing to 'temurin' for long-term support
          java-version: '11'

      - name: Build APK
        run: cd android && ./gradlew assembleRelease  # Fixed typo: "gradelew" → "gradlew"

      - name: Upload APK
        uses: actions/upload-artifact@v4  # Updated from v2 → v4
        with:
          name: app-release.apk 
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk 
